---
openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: jenna.galli@citizensbank.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/jegalli22/restAPI-sample/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /comments:
    get:
      summary: shows user all comments
      description: |
        shows all comments
      operationId: showComments
      responses:
        "200":
          description: successfully shows all comments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commentsObject'
        "400":
          description: failed to show all comments
    post:
      summary: adds a comment
      description: Adds a comment to the system
      operationId: addComment
      requestBody:
        description: comment to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/commentsObject'
      responses:
        "201":
          description: comment created
        "400":
          description: invalid input, object invalid
  /users:
    get:
      summary: shows user all users
      description: |
        shows all users
      operationId: showUsers
      responses:
        "200":
          description: successfully shows all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/usersObject'
        "400":
          description: failed to show all users
    post:
      summary: adds a user
      description: Adds a user to the system
      operationId: addUser
      requestBody:
        description: user to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/usersObject'
      responses:
        "201":
          description: user created
        "400":
          description: invalid input, object invalid
components:
  schemas:
    commentsObject:
      type: object
      properties:
        id:
          type: integer
          format: int64
        body:
          type: string
          example: some comment
        postId:
          type: integer
          format: int64
      description: |
        what is included in a comments object
    usersObject:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: first name
        lastName:
          type: string
          example: last name
      description: what is included in a users object
